version: "2"
run:
  concurrency: 8
linters:
  default: none
  enable:
    - decorder
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
  settings:
    decorder:
      dec-order:
        - type
        - const
        - var
        - func
    gocritic:
      enabled-tags:
        - diagnostic
        - opinionated
        - performance
        - style
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: 'unused-parameter: parameter \S+ seems to be unused, consider removing or renaming it as _'
      - linters:
          - revive
        text: 'empty-block: this block is empty, you can remove it'
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - default
        - prefix(github.com/badrchoubai)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
