version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: greeter 
    binary: greeter
    main: ./cmd/greeter/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "main.version={{.Version}}"

dockers:
  - image_templates:
    - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}' 
    - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest' 
    dockerfile: Dockerfile.goreleaser

changelog:
  sort: asc
  use: github
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: Other work
      order: 9999

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
